server:
  port: 8762

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: client-service-route
          uri: lb://client-service
          predicates:
            - Path=/clients-microservice/**
          filters:
            - RewritePath=/clients-microservice(?<path>/?.*), $\{path}
        - id: account-service-route
          uri: lb://account-service
          predicates:
            - Path=/accounts-microservice/**
          filters:
            - RewritePath=/accounts-microservice(?<path>/?.*), $\{path}
        - id: account-type-service-route
          uri: lb://account-type-service
          predicates:
            - Path=/account-types-microservice/**
          filters:
            - RewritePath=/account-types-microservice(?<path>/?.*), $\{path}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway

